on:
  workflow_dispatch:
  push

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: how-do-you/gh-actions@v0
        with:
          who-to-greet: 'How do you...'
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
