on:
  workflow_dispatch:
  push:

jobs:
  test_cargo:
    runs-on: ubuntu-latest
    name: Test Cargo script
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Cargo script
        id: cargo
        uses: how-do-you/gh-actions@v0
        with:
          script: 'cargo'
      - name: Get version number output
        run: echo "The version was ${{ steps.cargo.outputs.version }}"
